### ISSUE TITLE
對於 Stop 的查詢

### ISSUE THREAD

**Issue by CasparChou** [comdan66/evolution#1]
感謝 OA 大大提供了龐大的數據，想詢問對於 Stop 的資料有沒有儲存原始的 Fort ID 
由於我從 Java版的 API 取得到的 Stop ID 都只會是 Fort ID ， 所以想詢問有沒有保留那串 ID 的資料這樣

另外想問一個小問題，跑完全台灣這樣大的地方，是用了多少個 bot 花多少的時間去蒐集的 ?!

**Comment by oawu** [comment]
我是跟一群朋友在各縣市去做查詢耶，他們會整理回報給我各地經緯度，而在找尋 stop 時，其實會去參考 http://pokemongomap.info/ 這個網站，但我們是自己手動新增捏，沒有你說的 Fort ID ＠＠a
然後我沒有用 bot 捏，所以不知道 bot 會花多久時間，但是我們搜集了將近快兩個月有喔～

**Comment by CasparChou** [comment]
震驚！這個毅力！
